version: '3'

services:

  bot:
    build: .
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application &&
             python manage.py runbot
             "
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env


volumes:
  .:
  postgres_data:
  static_volume:
  media_volume:
