version: '3.8'


services:


  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always


  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env


  bot:
    build: .
    command: python manage.py runbot
    depends_on:
      - db
    restart: always


volumes:
  .:
  postgres_data:
  static_volume:
  media_volume:
